### 1: Import Pandas

### 2: Create DataFrame

      Name  Marks  Gender
0     Anju     90  Female
1   Ranjan     79    Male
2     Amit     89    Male
3    Priya     87  Female
4     Ravi     97    Male
5  Viabhav     91    Male
6    Suman     90  Female

### 3: Display Top 3 Rows

     Name  Marks  Gender
0    Anju     90  Female
1  Ranjan     79    Male
2    Amit     89    Male

### 4: Display Last 3 Rows

      Name  Marks  Gender
4     Ravi     97    Male
5  Viabhav     91    Male
6    Suman     90  Female

### 5: Find Shape of Dataset (Print Number of Rows & Number of Columns)

(7, 3)

Number of Rows 7
Number of Column 3

### 6: Get information about dataset like Total Number Rows, Total Number of Columns, Datatypes of Each Columns and memory requirement

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 296.0+ bytes

### 7: Check null values in dataset

Name      0
Marks     0
Gender    0
dtype: int64

### 8: Get overall stastistics about dataframe

           Marks
count   7.000000
mean   89.000000
std     5.385165
min    79.000000
25%    88.000000
50%    90.000000
75%    90.500000
max    97.000000

        Name      Marks Gender
count      7   7.000000      7
unique     7        NaN      2
top     Amit        NaN   Male
freq       1        NaN      4
mean     NaN  89.000000    NaN
std      NaN   5.385165    NaN
min      NaN  79.000000    NaN
25%      NaN  88.000000    NaN
50%      NaN  90.000000    NaN
75%      NaN  90.500000    NaN
max      NaN  97.000000    NaN

### 9: Find Unique values from Gender Column

array(['Female', 'Male'], dtype=object)

### 10: Find the number of unique value form Gender Column

2

### 11: Display count of unique values in Gender column

Male      4
Female    3
Name: Gender, dtype: int64

### 12: Short all the values from mark column

1    79
3    87
2    89
0    90
6    90
5    91
4    97
Name: Marks, dtype: int64

### 13: Find the total number of students marks between 90 to 100

      Name  Marks  Gender
0     Anju     90  Female
4     Ravi     97    Male
5  Viabhav     91    Male
6    Suman     90  Female

### 14: Find the total number of students marks between 90 to 100 using (Inclusive) between method

4

### 15: Find Average Marks

89.0

### 16: Apply Methods

0    45.0
1    39.5
2    44.5
3    43.5
4    48.5
5    45.5
6    45.0
Name: Marks, dtype: float64

      Name  Marks  Gender  Half Marks
0     Anju     90  Female        45.0
1   Ranjan     79    Male        39.5
2     Amit     89    Male        44.5
3    Priya     87  Female        43.5
4     Ravi     97    Male        48.5
5  Viabhav     91    Male        45.5
6    Suman     90  Female        45.0

0    45.0
1    39.5
2    44.5
3    43.5
4    48.5
5    45.5
6    45.0
Name: Marks, dtype: float64

0    4
1    6
2    4
3    5
4    4
5    7
6    5
Name: Name, dtype: int64

### 17: Map() Function

0    2
1    1
2    1
3    2
4    1
5    1
6    2
Name: Gender, dtype: int64

      Name  Marks  Gender  Half Marks  Male_Female
0     Anju     90  Female        45.0            2
1   Ranjan     79    Male        39.5            1
2     Amit     89    Male        44.5            1
3    Priya     87  Female        43.5            2
4     Ravi     97    Male        48.5            1
5  Viabhav     91    Male        45.5            1
6    Suman     90  Female        45.0            2

### 18: Drop Column (Half Marks & Male_Female)

### 19: Print all columns name

Index(['Name', 'Marks', 'Gender'], dtype='object')

RangeIndex(start=0, stop=7, step=1)

### 20: Sort the DataFrame as per Marks Column

      Name  Marks  Gender
4     Ravi     97    Male
5  Viabhav     91    Male
0     Anju     90  Female
6    Suman     90  Female
2     Amit     89    Male
3    Priya     87  Female
1   Ranjan     79    Male

      Name  Marks  Gender
4     Ravi     97    Male
5  Viabhav     91    Male
0     Anju     90  Female
6    Suman     90  Female
2     Amit     89    Male
3    Priya     87  Female
1   Ranjan     79    Male

### 21: Display Name and Marks of the female students

   Marks  Gender
0     90  Female
1     79    Male
2     89    Male
3     87  Female
4     97    Male
5     91    Male
6     90  Female

    Name  Marks
0   Anju     90
3  Priya     87
6  Suman     90

    Name  Marks
0   Anju     90
3  Priya     87
6  Suman     90