In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("real_estate_dataset.csv")
orgdata = data

In [3]:
data.head(3)

,Listing_ID,City,Locality,Property_Type,BHK,Area_Sqft,Price_INR,Price_Per_Sqft,Bedrooms,Bathrooms,Balconies,Property_Age,Floor,Total_Floors,Furnishing_Status,Parking_Available,Listing_Date,Owner_Type,Status,Contact_Number
0,RE100621,Ahmedabad,Dani Nagar,plot,2,1109.16,4948351.44,4461.35,Four,3.0,2.0,7,0,32.0,Semi-Furnished,NO,2022-04-12,Agent,SOLD,7936370284
1,RE104385,Mumbai,Jha Path,VILLA,4,1212.45,13989816.45,11538.47,NaN,4.0,3.0,26,11,16.0,UNFURNISHED,NO,2024-01-17,Individual,Available,1479774566
2,RE106794,Chennai,Roy Ganj,Penthouse,4,-500.00,9217000.55,-18434.00,2,4.0,NaN,22,16,24.0,Furnished,No,2023-07-18,builder,available,1953664041

In [4]:
data.shape

(10150, 20)

In [5]:
data.describe()

,Area_Sqft,Price_INR,Price_Per_Sqft,Bathrooms,Balconies,Total_Floors,Contact_Number
count,9948.000000,9.946000e+03,1.011700e+04,7967.000000,8132.000000,9899.000000,1.015000e+04
mean,1465.859202,1.415778e+07,1.101310e+04,2.499686,1.514019,22.653298,2.965995e+11
std,1435.124450,7.493310e+07,1.429533e+05,1.125099,1.116584,12.721928,4.247967e+11
min,-561.200000,-4.409279e+06,-1.043742e+07,1.000000,0.000000,1.000000,9.999900e+04
25%,1055.355000,6.159559e+06,4.030320e+03,1.000000,1.000000,11.000000,3.454136e+09
50%,1400.410000,8.546723e+06,6.005250e+03,3.000000,2.000000,23.000000,7.306648e+09
75%,1743.955000,1.090399e+07,8.731720e+03,4.000000,3.000000,34.000000,9.120576e+11
max,25000.000000,1.000000e+09,6.871908e+06,4.000000,3.000000,44.000000,9.199979e+11

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10150 entries, 0 to 10149
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Listing_ID         10150 non-null  object
 1   City               9950 non-null   object
 2   Locality           10150 non-null  object
 3   Property_Type      10150 non-null  object
 4   BHK                8844 non-null   object
 5   Area_Sqft          9948 non-null   float64
 6   Price_INR          9946 non-null   float64
 7   Price_Per_Sqft     10117 non-null  float64
 8   Bedrooms           8715 non-null   object
 9   Bathrooms          7967 non-null   float64
 10  Balconies          8132 non-null   float64
 11  Property_Age       9809 non-null   object
 12  Floor              10150 non-null  object
 13  Total_Floors       9899 non-null   float64
 14  Furnishing_Status  10150 non-null  object
 15  Parking_Available  8183 non-null   object
 16  Listing_Date       10150 non-null  object
 17  Owner_Type         10150 non-null  object
 18  Status             10150 non-null  object
 19  Contact_Number     10150 non-null  int64
dtypes: float64(6), int64(1), object(13)
memory usage: 1.5+ MB

In [7]:
# summing up column wise missing values
data.isnull().sum().sort_values(ascending=False)

Bathrooms            2183
Balconies            2018
Parking_Available    1967
Bedrooms             1435
BHK                  1306
Property_Age          341
Total_Floors          251
Price_INR             204
Area_Sqft             202
City                  200
Price_Per_Sqft         33
Listing_ID              0
Property_Type           0
Locality                0
Floor                   0
Furnishing_Status       0
Listing_Date            0
Owner_Type              0
Status                  0
Contact_Number          0
dtype: int64

In [8]:
# summing up row  wise missing values
data.isnull().sum(axis=1).sort_values(ascending=False)

6097     5
175      5
1424     5
1691     5
4230     5
        ..
10145    0
6724     0
6725     0
6728     0
6735     0
Length: 10150, dtype: int64

In [9]:
round(data.isnull().sum().sort_values(ascending=False)/len(data),2)*100

Bathrooms            22.0
Balconies            20.0
Parking_Available    19.0
Bedrooms             14.0
BHK                  13.0
Property_Age          3.0
Total_Floors          2.0
Price_INR             2.0
Area_Sqft             2.0
City                  2.0
Price_Per_Sqft        0.0
Listing_ID            0.0
Property_Type         0.0
Locality              0.0
Floor                 0.0
Furnishing_Status     0.0
Listing_Date          0.0
Owner_Type            0.0
Status                0.0
Contact_Number        0.0
dtype: float64

In [10]:
data['Bathrooms'].describe()

count    7967.000000
mean        2.499686
std         1.125099
min         1.000000
25%         1.000000
50%         3.000000
75%         4.000000
max         4.000000
Name: Bathrooms, dtype: float64

In [11]:
data.fillna({'Bathrooms': data['Bathrooms'].mean()}, inplace=True)

In [16]:
round(data.isnull().sum().sort_values(ascending=False)/len(data),2)*100

Parking_Available    19.0
Bedrooms             14.0
BHK                  13.0
Property_Age          3.0
Total_Floors          2.0
Price_INR             2.0
Area_Sqft             2.0
City                  2.0
Price_Per_Sqft        0.0
Property_Type         0.0
Listing_ID            0.0
Locality              0.0
Balconies             0.0
Bathrooms             0.0
Floor                 0.0
Furnishing_Status     0.0
Listing_Date          0.0
Owner_Type            0.0
Status                0.0
Contact_Number        0.0
dtype: float64

In [13]:
data.fillna({'Balconies': data['Balconies'].mean()}, inplace=True)

In [15]:
data['Parking_Available'].describe()

count     8183
unique       4
top         NO
freq      2118
Name: Parking_Available, dtype: object

In [18]:
print(data["Bedrooms"].unique())

['Four' nan '2' '5' '3' '4' '1']

In [19]:
mapping = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5,
    "Six": 6
}

data["Bedrooms"] = data["Bedrooms"].replace(mapping)

In [20]:
data["Bedrooms"] = pd.to_numeric(data["Bedrooms"], errors="coerce")

In [21]:
data["Bedrooms"].dtype

dtype('float64')

In [22]:
data["Bedrooms"] = data["Bedrooms"].fillna(data["Bedrooms"].median())

In [23]:
mapping = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

data["BHK"] = data["BHK"].replace(mapping)

data["BHK"] = data["BHK"].astype(str).str.replace("BHK", "", regex=False)

data["BHK"] = pd.to_numeric(data["BHK"], errors="coerce")

data["BHK"] = data["BHK"].fillna(data["BHK"].median())

In [24]:
data["City"] = data["City"].fillna(data["City"].mode()[0])
data["Area_Sqft"] = data["Area_Sqft"].fillna(data["Area_Sqft"].median())
data["Price_INR"] = data["Price_INR"].fillna(data["Price_INR"].median())
data["Bedrooms"] = data["Bedrooms"].fillna(data["Bedrooms"].median())

In [25]:
print(data["Bedrooms"].unique())
print(data["BHK"].unique())

[4. 2. 5. 3. 1.]
[2. 4. 1. 3. 5.]

In [27]:
print(data["Property_Age"].unique())

['7' '26' '22' '2' '10' '15' '1' nan '17' '13' '25' '24' '28' '9' '20'
 'New' '3' '23' '27' '21' '29' '6' '0' '11' '5' '18' '14' '19' '30' '4'
 '8' '12' '16']

In [28]:
data["Property_Age"] = data["Property_Age"].replace({
    "New": 0
})

In [30]:
data["Property_Age"] = pd.to_numeric(data["Property_Age"], errors="coerce")

In [31]:
data["Property_Age"] = data["Property_Age"].fillna(data["Property_Age"].median())

In [32]:
round(data.isnull().sum().sort_values(ascending=False)/len(data),2)*100

Parking_Available    19.0
Total_Floors          2.0
Price_Per_Sqft        0.0
Listing_ID            0.0
Property_Type         0.0
Locality              0.0
City                  0.0
BHK                   0.0
Bedrooms              0.0
Bathrooms             0.0
Area_Sqft             0.0
Price_INR             0.0
Property_Age          0.0
Balconies             0.0
Floor                 0.0
Furnishing_Status     0.0
Listing_Date          0.0
Owner_Type            0.0
Status                0.0
Contact_Number        0.0
dtype: float64

In [33]:
print(data["Parking_Available"].unique())

['NO' 'No' nan 'Yes' 'yes']

In [34]:
data["Parking_Available"] = (
    data["Parking_Available"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [35]:
print(data["Parking_Available"].unique())

['NO' 'NAN' 'YES']

In [36]:
import numpy as np

data["Parking_Available"] = data["Parking_Available"].replace("NAN", np.nan)

In [37]:
data["Parking_Available"] = data["Parking_Available"].fillna(
    data["Parking_Available"].mode()[0]
)

In [38]:
data["Total_Floors"] = pd.to_numeric(
    data["Total_Floors"], errors="coerce"
)

data["Total_Floors"] = data["Total_Floors"].fillna(
    data["Total_Floors"].median()
)

In [39]:
round(data.isnull().sum() / len(data) * 100, 2)

Listing_ID           0.00
City                 0.00
Locality             0.00
Property_Type        0.00
BHK                  0.00
Area_Sqft            0.00
Price_INR            0.00
Price_Per_Sqft       0.33
Bedrooms             0.00
Bathrooms            0.00
Balconies            0.00
Property_Age         0.00
Floor                0.00
Total_Floors         0.00
Furnishing_Status    0.00
Parking_Available    0.00
Listing_Date         0.00
Owner_Type           0.00
Status               0.00
Contact_Number       0.00
dtype: float64

In [40]:
len(data)/len(orgdata)*100

100.0

In [41]:
data.to_csv('Data_After_Cleaning.csv')