In [1]:
import pandas as pd

In [2]:

data = {
    "Name": ["Anju", "Ranjan", "Amit", "Priya", "Ravi", "Viabhav", "Suman"],
    "Marks": [90, 79, 89, 87, 97, 91, 90],
    "Gender": ["Female", "Male", "Male", "Female", "Male", "Male", "Female"]
}

df = pd.DataFrame(data)

print(df)

      Name  Marks  Gender
0     Anju     90  Female
1   Ranjan     79    Male
2     Amit     89    Male
3    Priya     87  Female
4     Ravi     97    Male
5  Viabhav     91    Male
6    Suman     90  Female

In [3]:
print(df.head(3))

     Name  Marks  Gender
0    Anju     90  Female
1  Ranjan     79    Male
2    Amit     89    Male

In [4]:
print(df.tail(3))

      Name  Marks  Gender
4     Ravi     97    Male
5  Viabhav     91    Male
6    Suman     90  Female

In [5]:
df.shape

(7, 3)

In [6]:

rows, columns = df.shape

print("Number of Rows", rows)
print("Number of Column", columns)

Number of Rows 7
Number of Column 3

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 296.0+ bytes

In [8]:
df.isnull().sum().sort_values(ascending=False)

Name      0
Marks     0
Gender    0
dtype: int64

In [9]:
df.describe()

           Marks
count   7.000000
mean   89.000000
std     5.385165
min    79.000000
25%    88.000000
50%    90.000000
75%    90.500000
max    97.000000

In [10]:
print(df.describe(include="all"))

        Name      Marks Gender
count      7   7.000000      7
unique     7        NaN      2
top     Anju        NaN   Male
freq       1        NaN      4
mean     NaN  89.000000    NaN
std      NaN   5.385165    NaN
min      NaN  79.000000    NaN
25%      NaN  88.000000    NaN
50%      NaN  90.000000    NaN
75%      NaN  90.500000    NaN
max      NaN  97.000000    NaN

In [11]:

print(df["Gender"].unique())

['Female' 'Male']

In [12]:
print(df["Gender"].nunique())

2

In [13]:
print(df["Gender"].value_counts())

Gender
Male      4
Female    3
Name: count, dtype: int64

In [14]:
print(df["Marks"].sort_values())

1    79
3    87
2    89
0    90
6    90
5    91
4    97
Name: Marks, dtype: int64

In [15]:
students = df[(df["Marks"] >= 90) & (df["Marks"] <= 100)]

print(students)

      Name  Marks  Gender
0     Anju     90  Female
4     Ravi     97    Male
5  Viabhav     91    Male
6    Suman     90  Female

In [16]:
print(len(df[(df["Marks"] >= 90) & (df["Marks"] <= 100)]))

4

In [17]:
print(df["Marks"].mean())

89.0

In [18]:
print(df["Marks"].apply(lambda x: x/2))

0    45.0
1    39.5
2    44.5
3    43.5
4    48.5
5    45.5
6    45.0
Name: Marks, dtype: float64

In [19]:

df["Half Marks"] = df["Marks"].apply(lambda x: x / 2)


print(df)

      Name  Marks  Gender  Half Marks
0     Anju     90  Female        45.0
1   Ranjan     79    Male        39.5
2     Amit     89    Male        44.5
3    Priya     87  Female        43.5
4     Ravi     97    Male        48.5
5  Viabhav     91    Male        45.5
6    Suman     90  Female        45.0

In [20]:
print(df["Name"].apply(lambda x: len(x)))

0    4
1    6
2    4
3    5
4    4
5    7
6    5
Name: Name, dtype: int64

In [21]:
print(df["Gender"].map({"Male": 1, "Female": 2}))

0    2
1    1
2    1
3    2
4    1
5    1
6    2
Name: Gender, dtype: int64

In [22]:
df["Male_Female"]=df["Gender"].map({"Male": 1, "Female": 2})
print(df)

      Name  Marks  Gender  Half Marks  Male_Female
0     Anju     90  Female        45.0            2
1   Ranjan     79    Male        39.5            1
2     Amit     89    Male        44.5            1
3    Priya     87  Female        43.5            2
4     Ravi     97    Male        48.5            1
5  Viabhav     91    Male        45.5            1
6    Suman     90  Female        45.0            2

In [23]:
df = df.drop(["Half Marks", "Male_Female"], axis=1)
print(df)

      Name  Marks  Gender
0     Anju     90  Female
1   Ranjan     79    Male
2     Amit     89    Male
3    Priya     87  Female
4     Ravi     97    Male
5  Viabhav     91    Male
6    Suman     90  Female

In [25]:
print(df.columns)

Index(['Name', 'Marks', 'Gender'], dtype='object')

In [26]:

df.sort_values(by="Marks", ascending=False)

      Name  Marks  Gender
4     Ravi     97    Male
5  Viabhav     91    Male
0     Anju     90  Female
6    Suman     90  Female
2     Amit     89    Male
3    Priya     87  Female
1   Ranjan     79    Male

In [27]:

df[df["Gender"] == "Female"][["Name", "Marks"]]

    Name  Marks
0   Anju     90
3  Priya     87
6  Suman     90