In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Housing_Data.csv")
orgdata = data

In [3]:
data.head(3)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03-09-16,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03-12-16,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04-02-16,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0

In [4]:
data.tail(3)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24-02-18,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24-02-18,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24-02-18,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [5]:
data.shape

(34857, 21)

In [6]:
data.describe()

,Rooms,Price,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,34857.000000,2.724700e+04,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,15551.000000,26881.000000,26881.000000,34854.000000
mean,3.031012,1.050173e+06,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,160.25640,1965.289885,-37.810634,145.001851,7572.888306
std,0.969933,6.414671e+05,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,401.26706,37.328178,0.090279,0.120169,4428.090313
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.350000e+05,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,102.00000,1940.000000,-37.862950,144.933500,4385.000000
50%,3.000000,8.700000e+05,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.00000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.295000e+06,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,188.00000,2000.000000,-37.754100,145.071900,10412.000000
max,16.000000,1.120000e+07,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.00000,2106.000000,-37.390200,145.526350,21650.000000

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   SellerG        34857 non-null  object
 7   Date           34857 non-null  object
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom        26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  object
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 5.6+ MB

In [8]:
# summing up column wise missing values
data.isnull().sum().sort_values(ascending=False)

BuildingArea     21115
YearBuilt        19306
Landsize         11810
Car               8728
Bathroom          8226
Bedroom           8217
Lattitude         7976
Longtitude        7976
Price             7610
Regionname           3
CouncilArea          3
Propertycount        3
Distance             1
Postcode             1
Rooms                0
Address              0
Suburb               0
Type                 0
SellerG              0
Date                 0
Method               0
dtype: int64

In [9]:
# summing up row  wise missing values
data.isnull().sum(axis=1).sort_values(ascending=False)

29483    13
18523    11
26888    11
34745     9
28717     9
         ..
59        0
61        0
63        0
66        0
67        0
Length: 34857, dtype: int64

In [10]:
# summing up column wise missing values in percentage 

round(data.isnull().sum().sort_values(ascending=False)/len(data),2)*100

BuildingArea     61.0
YearBuilt        55.0
Landsize         34.0
Car              25.0
Bathroom         24.0
Bedroom          24.0
Lattitude        23.0
Longtitude       23.0
Price            22.0
Regionname        0.0
CouncilArea       0.0
Propertycount     0.0
Distance          0.0
Postcode          0.0
Rooms             0.0
Address           0.0
Suburb            0.0
Type              0.0
SellerG           0.0
Date              0.0
Method            0.0
dtype: float64

In [11]:
data = data.drop(['BuildingArea','YearBuilt'],axis=1)

In [12]:
data.shape

(34857, 19)

In [13]:
data.isnull().sum(axis=1)>5

0        False
1        False
2        False
3        False
4        False
         ...
34852    False
34853    False
34854    False
34855     True
34856    False
Length: 34857, dtype: bool

In [14]:
len(data[data.isnull().sum(axis=1)>5])/len(data)*100

22.80747052242017

In [15]:
len(data[data.isnull().sum(axis=1)<5])/len(data)*100

77.02900421723041

In [16]:
data = data[data.isnull().sum(axis=1)<5]

In [17]:
data.shape

(26850, 19)

In [18]:
data = data[data['Price'].notnull()]

In [19]:
round(data.isnull().sum().sort_values(ascending= False)/len(data)*100,2)

Landsize         14.43
Car               2.82
Bathroom          1.02
Bedroom           0.99
Lattitude         0.10
Longtitude        0.10
Suburb            0.00
Rooms             0.00
Address           0.00
Method            0.00
Type              0.00
Postcode          0.00
Distance          0.00
Date              0.00
SellerG           0.00
Price             0.00
CouncilArea       0.00
Regionname        0.00
Propertycount     0.00
dtype: float64

In [20]:
data = data[data['Landsize'].notnull()]

In [21]:
round(data.isnull().sum().sort_values(ascending= False)/len(data)*100,2)

Car              1.56
Lattitude        0.12
Longtitude       0.12
Bathroom         0.05
Bedroom          0.03
Suburb           0.00
Address          0.00
Rooms            0.00
Type             0.00
Method           0.00
Price            0.00
Postcode         0.00
Distance         0.00
Date             0.00
SellerG          0.00
CouncilArea      0.00
Landsize         0.00
Regionname       0.00
Propertycount    0.00
dtype: float64

In [22]:
data.shape

(17982, 19)

In [23]:
data['Lattitude'].describe()

count    17960.000000
mean       -37.806490
std          0.089034
min        -38.190430
25%        -37.858900
50%        -37.800020
75%        -37.750170
max        -37.399460
Name: Lattitude, dtype: float64

In [24]:
data['Longtitude'].describe()

count    17960.000000
mean       144.995942
std          0.116992
min        144.423790
25%        144.925300
50%        145.002000
75%        145.066800
max        145.526350
Name: Longtitude, dtype: float64

In [25]:
data.loc[:,['Longtitude','Lattitude']].describe()

         Longtitude     Lattitude
count  17960.000000  17960.000000
mean     144.995942    -37.806490
std        0.116992      0.089034
min      144.423790    -38.190430
25%      144.925300    -37.858900
50%      145.002000    -37.800020
75%      145.066800    -37.750170
max      145.526350    -37.399460

In [26]:
data['Longtitude'].mean()

np.float64(144.99594155790643)

In [27]:
data['Lattitude'].mean()

np.float64(-37.80649038028953)

In [32]:
data.fillna({'Lattitude': data['Lattitude'].mean()}, inplace=True)

In [33]:
data.fillna({'Longtitude': data['Longtitude'].mean()},inplace=True)

In [34]:
data.shape

(17982, 19)

In [35]:
round(data.isnull().sum().sort_values(ascending= False)/len(data)*100,2)

Car              1.56
Bathroom         0.05
Bedroom          0.03
Rooms            0.00
Address          0.00
Suburb           0.00
Type             0.00
SellerG          0.00
Date             0.00
Method           0.00
Price            0.00
Postcode         0.00
Distance         0.00
Landsize         0.00
CouncilArea      0.00
Lattitude        0.00
Longtitude       0.00
Regionname       0.00
Propertycount    0.00
dtype: float64

In [36]:
data.loc[:,['Bathroom','Bedroom']].describe()

           Bathroom       Bedroom
count  17973.000000  17976.000000
mean       1.580871      3.033100
std        0.702912      0.954873
min        0.000000      0.000000
25%        1.000000      2.000000
50%        1.000000      3.000000
75%        2.000000      4.000000
max        9.000000     20.000000

In [37]:
data['Bathroom'].astype('category').value_counts()

Bathroom
1.0    9275
2.0    7145
3.0    1308
4.0     154
5.0      43
0.0      34
6.0       9
7.0       2
8.0       2
9.0       1
Name: count, dtype: int64

In [38]:
data.fillna({'Bathroom': 1},inplace=True)

In [39]:
data['Bedroom'].astype('category').value_counts()

Bedroom
3.0     8104
2.0     4129
4.0     4060
5.0      842
1.0      704
6.0       91
0.0       16
7.0       14
8.0        7
10.0       4
9.0        3
12.0       1
20.0       1
Name: count, dtype: int64

In [40]:
data.fillna({'Bedroom': 3},inplace=True)

In [41]:
data['Car'].describe()

count    17701.000000
mean         1.698887
std          0.998673
min          0.000000
25%          1.000000
50%          2.000000
75%          2.000000
max         18.000000
Name: Car, dtype: float64

In [42]:
data['Car'].astype('category').value_counts()

Car
2.0     7970
1.0     6483
0.0     1178
3.0     1065
4.0      778
5.0       99
6.0       92
7.0       16
8.0       12
10.0       4
9.0        2
11.0       1
18.0       1
Name: count, dtype: int64

In [43]:
data.fillna({'Car': 2},inplace=True)

In [44]:
round(data.isnull().sum().sort_values(ascending= False)/len(data)*100,2)

Suburb           0.0
Address          0.0
Rooms            0.0
Type             0.0
Price            0.0
Method           0.0
SellerG          0.0
Date             0.0
Distance         0.0
Postcode         0.0
Bedroom          0.0
Bathroom         0.0
Car              0.0
Landsize         0.0
CouncilArea      0.0
Lattitude        0.0
Longtitude       0.0
Regionname       0.0
Propertycount    0.0
dtype: float64

In [45]:
len(data)/len(orgdata)*100

51.58791634391944

In [46]:
data.to_csv('Data_After_Cleaning.csv')